name: Test on macOS 14 arm64

on: [ push,workflow_dispatch,workflow_call ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build & Test arm64-aarch64 mainnet
        timeout-minutes: 10
        run: |
          git fetch -a
          git checkout arm64-aarch64
          mkdir artifacts
          mvn clean compile package -DskipTests
          cp target/MyLocalTon.jar artifacts/MyLocalTon-arm64.jar
          java -jar artifacts/MyLocalTon-arm64.jar nogui debug test-binaries

      - name: Build & Test arm64-aarch64 testnet
        timeout-minutes: 10
        run: |
          mvn clean compile package -DskipTests -Dton_branch=testnet
          cp target/MyLocalTon.jar artifacts/MyLocalTon-arm64-testnet.jar
          java -jar artifacts/MyLocalTon-arm64-testnet.jar nogui debug test-binaries

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: All-MyLocalTon-Jars
          path: artifacts
